### ISSUE TITLE
Comparison with bs58check

### ISSUE THREAD

**Issue by dcousens** [wzbg/base58check#1]
Out of curiosity,  is there any intended difference between this module and https://github.com/bitcoinjs/bs58check?

**Comment by wzbg** [comment]
bs58check.encode‘s input is prefix+data Buffers, this module's input is data & prefix & encoding.
so bs58check.encode(new Buffer('00f5f2d624cfb5c3f66d06123d0829d1c9cebf770e', 'hex')) == base58check('f5f2d624cfb5c3f66d06123d0829d1c9cebf770e', '00', 'hex') or base58check(new Buffer('f5f2d624cfb5c3f66d06123d0829d1c9cebf770e', 'hex'), '00', 'hex').
Thank you for your question, I will improve it.

**Comment by dcousens** [comment]
I like how you dealt with prefixes :+1:
